[project]
name = "your-personal-ai-nutritionist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=4.3.0",
    "sqlalchemy>=2.0.41",
    "streamlit>=1.45.1",
    "stripe>=12.1.0",
]


